export const theme = {
  colors: {
    primary: '#4734c3',
    secondary: '#9f402d',
    tertiary: '#005a40',
    background: '#fdf9f3',
    surface: '#fdf9f3',
    'surface-container': '#f1ede7',
    'surface-container-low': '#f7f3ed',
    'surface-container-high': '#ebe8e2',
    'surface-container-highest': '#e6e2dc',
    'on-surface': '#1c1c18',
    'on-surface-variant': '#474554',
    outline: '#787586',
    'outline-variant': '#c8c4d7',
    gold: '#D4AF37',
    white: '#ffffff',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    gutter: 16,
    'margin-mobile': 20,
    unit: 4,
  },
  borderRadius: {
    DEFAULT: 4,
    md: 8,
    lg: 8,
    xl: 12,
    '2xl': 24,
    full: 9999,
  },
  typography: {
    'body-lg': { fontFamily: 'NotoSans_400Regular', fontSize: 18, lineHeight: 28 },
    'body-md': { fontFamily: 'NotoSans_400Regular', fontSize: 16, lineHeight: 24 },
    'display-lg': { fontFamily: 'HankenGrotesk_700Bold', fontSize: 32, lineHeight: 40, letterSpacing: -0.64 },
    'headline-md': { fontFamily: 'HankenGrotesk_600SemiBold', fontSize: 24, lineHeight: 32 },
    'headline-sm': { fontFamily: 'HankenGrotesk_600SemiBold', fontSize: 20, lineHeight: 28 },
    'label-md': { fontFamily: 'NotoSans_500Medium', fontSize: 14, lineHeight: 20, letterSpacing: 0.14 },
    'label-sm': { fontFamily: 'NotoSans_600SemiBold', fontSize: 12, lineHeight: 16 },
    arabic: { fontFamily: 'Amiri_400Regular', fontSize: 18 },
    calligraphy: { fontFamily: 'Amiri_700Bold', fontSize: 24 },
  }
} as const;
